version: "3.3"

services:
  weather:
    build:
      context: .
    container_name: weather
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://weather:password@db:5432/weather?schema=public
      - NUXT_WEATHER_API_KEY=d390c0169f7be71a1f71aadef2488487 # this api key is revoked
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=weather
  db:
    container_name: db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=weather
      - POSTGRES_DB=weather
    volumes:
      - database-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U weather"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - weather

volumes:
  database-data:
